export const personal = {
  name: "Rohit Raj",
  title: "Game Designer",
  tagline: "Crafting player experiences through systems, mechanics & intuitive design.",
  email: "Choudharyrohit2699@gmail.com",
  phone: "+91 84530 08641",
  linkedin: "https://www.linkedin.com/in/rohit-choudhary-/",
  linkedinLabel: "Rohit Choudhary",
  location: "India",
};

export const about = {
  bio: [
    "I'm a Game Designer passionate about creating engaging, intuitive player experiences. I specialise in gameplay systems, level design, and balancing fun with challenge — turning ideas into mechanics that feel just right.",
    "I've shipped multiple titles across casual, puzzle, and action genres, working with cross-functional teams to deliver polished games on tight timelines. Currently exploring narrative systems and procedural design in personal projects using Godot and Unity.",
  ],
  highlights: [
    { value: "8+", label: "Games Shipped" },
    { value: "3+", label: "Years Experience" },
    { value: "3", label: "Personal Projects" },
  ],
};

export const games = [
  {
    id: 1,
    title: "Chef Tycoon",
    genre: "Casual / Management",
    role: "Game Designer · Level Designer · UI/UX · Game Mathematician",
    description: "A fast-paced kitchen management game where players build and optimise their restaurant empire. Designed progression systems, economy loops, and difficulty curves.",
    link: "https://www.gamezop.com/en/game/chef-tycoon/xqO4nZ6Kt",
    tags: ["Systems Design", "Economy", "Progression"],
    year: "2023",
  },
  {
    id: 2,
    title: "Assassin's Hunt: Wild West",
    genre: "Action / Shooter",
    role: "Game Designer · Level Designer · UI/UX · Game Mathematician",
    description: "A western-themed action shooter. Responsible for enemy AI behaviour, level flow, and pacing to create satisfying gunfight encounters.",
    link: "https://www.gamezop.com/en/game/assassins-hunt-wild-west/9lpHai56Q",
    tags: ["Level Design", "AI Design", "Combat Feel"],
    year: "2023",
  },
  {
    id: 3,
    title: "Blocks Adventure: Jungle Saga",
    genre: "Puzzle / Adventure",
    role: "Game Designer · Level Designer · UI/UX",
    description: "A block-sliding puzzle adventure set in lush jungle environments. Designed 60+ puzzle levels with escalating complexity and introduced new mechanics per world.",
    link: "https://www.gamezop.com/en/game/blocks-adventure-jungle-saga/UCS62KJ8c",
    tags: ["Puzzle Design", "Level Design", "Difficulty Tuning"],
    year: "2023",
  },
  {
    id: 4,
    title: "Tower Buster",
    genre: "Arcade / Action",
    role: "Game Designer · Level Designer · UI/UX · Game Mathematician",
    description: "A kinetic arcade game focused on destruction physics and combo systems. Designed scoring loops and player feedback systems to maximise satisfaction.",
    link: "https://www.gamezop.com/en/game/tower-buster/8WGtd7TLH",
    tags: ["Arcade Design", "Feedback Systems", "Scoring"],
    year: "2023",
  },
  {
    id: 5,
    title: "Harbor Dash",
    genre: "Casual / Runner",
    role: "Game Designer · Level Designer · UI/UX · Game Mathematician",
    description: "A whimsical endless runner set in a bustling harbour. Designed obstacle patterns, power-up systems, and the risk-reward framework that drives replayability.",
    link: "https://www.gamezop.com/en/game/harbor-dash/Nr1P9rmbi",
    tags: ["Endless Runner", "Power-ups", "Replayability"],
    year: "2023",
  },
  {
    id: 6,
    title: "Bubble Shooter Classic",
    genre: "Puzzle / Casual",
    role: "Game Designer · Level Designer · UI/UX",
    description: "A refined take on the timeless bubble shooter formula. Focused on level pacing, colour theory in puzzle generation, and accessibility tuning.",
    link: "https://www.gamezop.com/en/game/bubble-shooter-classic/yVywAGBQ6",
    tags: ["Puzzle Design", "Accessibility", "Casual"],
    year: "2023",
  },
  {
    id: 7,
    title: "Dragon Annihilation",
    genre: "Action / Fantasy",
    role: "Game Designer · Level Designer · UI/UX · Game Mathematician",
    description: "An intense fantasy action game featuring dragon combat. Led encounter design, boss phase structure, and ability balancing across 20+ stages.",
    link: "https://www.gamezop.com/en/game/dragon-annihilation/PdIZyZNAe",
    tags: ["Encounter Design", "Boss Design", "Balancing"],
    year: "2023",
  },
  {
    id: 8,
    title: "Sudoku Classic",
    genre: "Puzzle / Logic",
    role: "Game Designer",
    description: "A clean, focused digital sudoku experience. Designed the hint system, difficulty tiers, and the onboarding flow to welcome new players to the genre.",
    link: "https://www.gamezop.com/en/game/sudoku-classic/SJgx126Qc0H",
    tags: ["UX Design", "Onboarding", "Hint Systems"],
    year: "2023",
  },
  {
    id: 9,
    title: "Tripple Tile Match Master",
    genre: "Puzzle / Casual",
    role: "Game Designer · Level Designer · UI/UX · Game Mathematician",
    description: "A strategic tile-matching puzzle game where players manage a limited tray of assets, clearing levels by grouping three identical tiles before the tray fills up. Designed the core match- three loop, 100 + hand crafted levels with escalating complexity, economy & progression systems, and the full UI / UX flow from onboarding to level complete screens.",
    link: "https://www.gamezop.com/en/game/triple-tile-match-master/kWnZGIWIJ",
    tags: ["Level Design", "Systems Design", "UI/UX", "Puzzle Design", "Economy"],
    year: "2025",
  },
  {
    id: 10,
    title: "Void",
    genre: "Personal Project",
    role: "Designer & Developer",
    description: "An original game built in Godot, currently in active development. Exploring narrative mechanics, environmental storytelling, and custom shaders.",
    link: null,
    linkLabel: "Coming Soon",
    tags: ["Godot", "Narrative", "In Development"],
    year: "2025",
    wip: true,
  },
  {
    id: 11,
    title: "Unity Prototype",
    genre: "Personal Project",
    role: "Designer & Developer",
    description: "A gameplay prototype built in Unity, demonstrating core loop design and rapid iteration from paper prototype to playable build.",
    link: null,
    linkLabel: "Video Available",
    tags: ["Unity", "Prototyping", "Core Loop"],
    year: "2024",
    wip: true,
  },
];

export const skills = [
  {
    category: "Design",
    items: ["Game Systems Design", "Level Design", "Economy & Progression Design", "Narrative Design", "UX / Player Psychology", "Balancing & Tuning", "Paper Prototyping"],
  },
  {
    category: "Tools",
    items: ["Unity", "Godot", "Figma", "Miro", "Google Sheets (Balancing)", "Jira / Confluence", "Adobe XD"],
  },
  {
    category: "Disciplines",
    items: ["Casual & Hyper-casual", "Puzzle Design", "Action / Arcade", "Mobile Game Design", "Cross-functional Collaboration", "Agile / Scrum", "Documentation"],
  },
];
